'use client';

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import Link from "next/link";
import { Provider } from 'react-redux';
import { store } from '../store/store'; // Path to your Redux store
import Head from 'next/head';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <Provider store={store}>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Head>
            <title>Art Business</title>
            <meta name="description" content={metadata.description} />
          </Head>

          <header className="bg-white shadow-md py-4">
            <div className="container mx-auto flex justify-between items-center px-4 sm:px-6 lg:px-8">
              <div className="logo">
                <Link href="/" className="text-lg sm:text-2xl font-bold text-gray-700">
                  ArtBusiness
                </Link>
              </div>
              <nav>
                <ul className="flex space-x-4 sm:space-x-6">
                  <li>
                    <Link href="/" className="text-gray-700 hover:text-gray-900">
                      Home
                    </Link>
                  </li>
                  <li>
                    <Link href="/about" className="text-gray-700 hover:text-gray-900">
                      About
                    </Link>
                  </li>
                  <li>
                    <Link href="/arts" className="text-gray-700 hover:text-gray-900">
                      Gallery
                    </Link>
                  </li>
                  <li>
                    <Link href="/contact" className="text-gray-700 hover:text-gray-900">
                      Contact
                    </Link>
                  </li>
                </ul>
              </nav>
            </div>
          </header>

          <main className="container mx-auto px-4 sm:px-6 lg:px-8 py-8">
            {children}
          </main>

          <footer className="bg-gray-900 text-white py-8 px-4 sm:px-6 lg:px-8">
            <div className="container mx-auto flex flex-col sm:flex-row justify-between items-center">
              <div className="text-center sm:text-left">
                <p>&copy; 2024 ArtBusiness</p>
                <p>123 Art St, City, Country</p>
                <p>contact@artbusiness.com</p>
              </div>
              <div className="mt-4 sm:mt-0 space-x-6">
                <a href="#" className="hover:text-teal-500">Instagram</a>
                <a href="#" className="hover:text-teal-500">Facebook</a>
                <a href="#" className="hover:text-teal-500">Pinterest</a>
              </div>
            </div>
          </footer>
        </body>
      </html>
    </Provider>
  );
}